spring.datasource.url=jdbc:postgresql://localhost:5432/srm_credit_engine
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create

spring.sql.init.mode=always
spring.sql.init.continue-on-error=false
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jpa.open-in-view=false